### ISSUE TITLE
Recover code coverage in GitHub Actions

### ISSUE THREAD

**Issue by yeraydavidrodriguez** [boken-engine/boken-engine#131]
When Boken was ported to Swift Package, the code coverage was lost when implementing required Workflow changes.

It would be nice to recover it.

**Comment by josecelano** [comment]
Relates to: https://github.com/boken-engine/boken-engine/issues/143

I can generate code coverage with this command:

```s
xcodebuild test -scheme BokenEngine -destination "platform=iOS Simulator,name=iPhone 11" -enableCodeCoverage YES
```

Last output lines

```s
Test session results, code coverage, and logs:
	/Users/josecelano/Library/Developer/Xcode/DerivedData/boken-engine-fdduicohdbncxfcimhhcymmybudc/Logs/Test/Test-BokenEngine-2022.06.22_12-52-09-+0100.xcresult

** TEST SUCCEEDED **
```

I suppose we can follow this tutorial:

https://theswiftdev.com/code-coverage-for-swift-package-manager-based-apps/

Or try to find an action on the marketplace.

It seems that you could also show the coverage report with something like:

```s
xcrun llvm-cov show --instr-profile=...
```

But I do not know which file that command expects.

**Comment by josecelano** [comment]
I managed to print coverage for one file with:

1. Test with option coverage

```s
xcodebuild test -scheme BokenEngine -destination "platform=iOS Simulator,name=iPhone 11" -enableCodeCoverage=YES -derivedDataPath=.DeriveData
```

NOTICE: argument `-derivedDataPath=.DeriveData` to use the project root folder for output artefacts.

2. Print text report for one file

```s
% xcrun llvm-cov report --format=text --instr-profile=".DeriveData/Build/ProfileData/860AB2C1-6615-42E7-93A8-9067DF75E7BA/Coverage.profdata" --object=.DeriveData/Build/Intermediates.noindex/BokenEngine.build/Debug-iphonesimulator/BokenEngine.build/Objects-normal/arm64/AudioManager.o
Filename                                                                                                        Regions    Missed Regions     Cover   Functions  Missed Functions  Executed       Lines      Missed Lines     Cover    Branches   Missed Branches     Cover
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/Users/josecelano/Documents/github/boken-engine/boken-engine/Sources/BokenEngine/Classes/AudioManager.swift          31                13    58.06%           7                 2    71.43%          66                18    72.73%           0                 0         -
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                                                31                13    58.06%           7                 2    71.43%          66                18    72.73%           0                 0         -

```

It seems you have to [combine all files manually](https://stackoverflow.com/a/66384683/3012842) to generate the full report.

**Comment by josecelano** [comment]
This is the final command for the full report:

```s
xcodebuild test \
    -scheme BokenEngine \
    -destination "platform=iOS Simulator,name=iPhone 11" \
    -enableCodeCoverage=YES \
    -derivedDataPath=.DeriveData
ld -r \
    -o ./CombinedObject.o .DeriveData/Build/Intermediates.noindex/BokenEngine.build/Debug-iphonesimulator/BokenEngine.build/Objects-normal/arm64/*.o
xcrun llvm-cov report \
    --format=text \
    --instr-profile=".DeriveData/Build/ProfileData/860AB2C1-6615-42E7-93A8-9067DF75E7BA/Coverage.profdata" \
    --object="./CombinedObject.o"
```

Output:

```s
Filename                      Regions    Missed Regions     Cover   Functions  Missed Functions  Executed       Lines      Missed Lines     Cover    Branches   Missed Branches     Cover
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
AppDescription.swift               20                 1    95.00%          10                 0   100.00%          55                 1    98.18%           0                 0         -
AudioManager.swift                 31                13    58.06%           7                 2    71.43%          66                18    72.73%           0                 0         -
ElementFactory.swift               87                20    77.01%          30                 6    80.00%         237                11    95.36%           0                 0         -
GesturesManager.swift               9                 1    88.89%           3                 0   100.00%          22                 2    90.91%           0                 0         -
RotationManager.swift              10                 1    90.00%           4                 0   100.00%          37                 1    97.30%           0                 0         -
SceneFactory.swift                 88                30    65.91%          30                 7    76.67%         213                49    77.00%           0                 0         -
SceneManager.swift                 42                 1    97.62%          20                 0   100.00%          93                 2    97.85%           0                 0         -
StoryParser.swift                  29                11    62.07%           8                 2    75.00%          57                14    75.44%           0                 0         -
TouchSpriteNode.swift               5                 2    60.00%           5                 2    60.00%          13                 6    53.85%           0                 0         -
UIColorExtension.swift              7                 0   100.00%           7                 0   100.00%          23                 0   100.00%           0                 0         -
Utils.swift                        26                10    61.54%           7                 0   100.00%          65                12    81.54%           0                 0         -
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
TOTAL                             354                90    74.58%         131                19    85.50%         881               116    86.83%           0                 0         -
```

If we want to use it on the test workflow we need to find a way to obtain the name of this folder `860AB2C1-6615-42E7-93A8-9067DF75E7BA`. If there is only one after the building is going to be easier.

**Comment by josecelano** [comment]
It seems we were using this action in the past:

```s
- name: Test Coverage
  uses: sersoft-gmbh/swift-coverage-action@v2
    with:
      search-paths: ./output 
```

@yeraydavidrodriguez do you remember why you removed it? It seems you were testing two different actions.

- xcodebuild-lcov-action
- sersoft-gmbh/swift-coverage-action
- spm-lcov-action

It seems you removed for some reason:

```
% git lol | grep coverage
* 0623d14 - Remove temporarily the code coverage measurement (2021-08-26 10:01:56 +0100) <yeraydavidrodriguez>
* 3b4cc58 - Try alternative coverage method (2021-08-26 10:01:56 +0100) <yeraydavidrodriguez>
* 4530460 - Remove coverage option from build step (2021-08-26 10:01:56 +0100) <yeraydavidrodriguez>
* 1828dff - Modify coverage action (2021-08-26 10:01:56 +0100) <yeraydavidrodriguez>
| | * f61f4c0 - Remove temporarily the code coverage measurement (2021-08-25 13:11:45 +0100) <yeraydavidrodriguez>
| | * 06f318d - Try alternative coverage method (2021-08-25 07:51:25 +0100) <yeraydavidrodriguez>
| | * 755a84d - Remove coverage option from build step (2021-08-25 07:33:22 +0100) <yeraydavidrodriguez>
| | * ee43973 - Modify coverage action (2021-08-25 07:29:20 +0100) <yeraydavidrodriguez>
| | * fe00de9 - (swift-5) Rollback to the previous coverage report action plugin (2021-08-12 18:13:22 +0100) <Jose Celano>
| | * 8706a95 - Rollback check coverage to job step to fix coverage report error (2021-08-12 18:08:54 +0100) <Jose Celano>
| | * 167750b - Fix coverage error. Test must be execute before (2021-08-12 18:00:33 +0100) <Jose Celano>
```

**Comment by josecelano** [comment]
I think we could try this action: https://github.com/marketplace/actions/xcodebuild-coverage-report

**Comment by josecelano** [comment]
I have found this Ruby gem: https://github.com/SlatherOrg/slather
It seems it could be used even with GitHub Actions. I installed and tried to use this way:

```s
slather coverage -s --scheme BokenEngine --build-directory ".DerivedData" --binary-file "./CombinedObject.o"
```

But it seems it requires project configuration:

```s
Slathering...
/Users/josecelano/.rvm/gems/ruby-3.0.0/gems/slather-2.7.2/lib/slather/command/coverage_command.rb:110:in `project': Must provide an xcodeproj either via the 'slather [SUBCOMMAND] [PROJECT].xcodeproj' command or through .slather.yml (StandardError)
	from /Users/josecelano/.rvm/gems/ruby-3.0.0/gems/slather-2.7.2/lib/slather/command/coverage_command.rb:67:in `setup_build_directory'
	from /Users/josecelano/.rvm/gems/ruby-3.0.0/gems/slather-2.7.2/lib/slather/command/coverage_command.rb:44:in `execute'
	from /Users/josecelano/.rvm/gems/ruby-3.0.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /Users/josecelano/.rvm/gems/ruby-3.0.0/gems/clamp-1.3.2/lib/clamp/subcommand/execution.rb:18:in `execute'
	from /Users/josecelano/.rvm/gems/ruby-3.0.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /Users/josecelano/.rvm/gems/ruby-3.0.0/gems/clamp-1.3.2/lib/clamp/command.rb:140:in `run'
	from /Users/josecelano/.rvm/gems/ruby-3.0.0/gems/slather-2.7.2/bin/slather:17:in `<top (required)>'
	from /Users/josecelano/.rvm/gems/ruby-3.0.0/bin/slather:23:in `load'
	from /Users/josecelano/.rvm/gems/ruby-3.0.0/bin/slather:23:in `<main>'
```ç

I have opened an [issue](https://github.com/SlatherOrg/slather/issues/515) on the repo to ask if it's possible to use it without setting up an Xcode project.

**Comment by josecelano** [comment]
For some reason the command to run tests with coverage does not work on the runner:

```s
/Applications/Xcode_13.3.1.app/Contents/Developer/usr/bin/xcodebuild test -scheme BokenEngine -destination "platform=iOS Simulator,name=iPhone 11" -enableCodeCoverage YES -derivedDataPath .DerivedData
```

The command: https://github.com/boken-engine/boken-engine/runs/7037978166?check_suite_focus=true#step:4:27
The error: https://github.com/boken-engine/boken-engine/runs/7037978166?check_suite_focus=true#step:4:56

Error:

```s
2022-06-24 08:05:12.553 xcodebuild[1861:25223] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-20103/IDEFoundation/Execution/RunContextManager/IDERunContextManager.m:823
Details:  Error deleting scheme: Cannot modify data because the process disallows saving.
Object:   <IDERunContextManager: 0x600000fd97a0>
Method:   -deleteRunContexts:completionQueue:completionBlock:
Thread:   <_NSMainThread: 0x[60](https://github.com/boken-engine/boken-engine/runs/7037978166?check_suite_focus=true#step:4:61)00028ec400>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com/ with this warning message and any useful information you can provide.
2022-06-24 08:05:12.554 xcodebuild[1861:2[52](https://github.com/boken-engine/boken-engine/runs/7037978166?check_suite_focus=true#step:4:53)23] could not delete old scheme: Error Domain=DVTCustomDataStoringErrors Code=0 "Cannot modify data because the process disallows saving." UserInfo={NSLocalizedDescription=Cannot modify data because the process disallows saving.}
```

I have opened a question on [stackoverflow.com](https://stackoverflow.com/q/72741060/3012842).
